# BrokerRPCMon status and exit codes

STATUS_OK=0
STATUS_WARNING=1
STATUS_CRITICAL=2
STATUS_CONFIG_ERROR=3
STATUS_BROKER_UNREACHABLE=4
STATUS_NOT_REGISTERED=5
STATUS_PING_FAILED=6
STATUS_PROCESS_DOWN=7
STATUS_MAINTENANCE=8
STATUS_UNKNOWN=9
